import { Psychologist } from './types';

export const psychologists: Psychologist[] = [
  {
    id: '1',
    name: 'María García Rodríguez',
    prefix: 'Dra.',
    slug: 'maria-garcia-rodriguez',
    initials: 'MG',
    avatarColor: '#6D28D9',
    primarySpecialty: 'Ansiedad y Estrés',
    specialty: 'Ansiedad y Estrés',
    specialties: ['Ansiedad y Estrés', 'Depresión', 'Mindfulness', 'Burnout'],
    rating: 4.9,
    reviewCount: 127,
    neighborhood: 'Altabrisa',
    location: 'Altabrisa, Mérida',
    address: 'Calle 20 #450, Col. Altabrisa, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Autónoma de Yucatán (UADY)', year: '2008' },
      { degree: 'Maestría en Psicología Clínica', institution: 'Universidad Nacional Autónoma de México (UNAM)', year: '2011' },
      { degree: 'Certificación en Terapia Cognitivo-Conductual', institution: 'Instituto Beck de México', year: '2013' },
    ],
    cedula: '8234567',
    yearsExperience: 15,
    pricePerSession: 900,
    price: 900,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Soy psicóloga clínica especializada en el tratamiento de ansiedad, estrés y burnout. Con más de 15 años de experiencia, he acompañado a cientos de pacientes a recuperar su bienestar emocional y calidad de vida. Mi enfoque es la Terapia Cognitivo-Conductual (TCC) combinada con técnicas de mindfulness, adaptadas a las necesidades únicas de cada persona. Creo firmemente que pedir ayuda es el primer paso hacia una vida más plena, y me comprometo a ofrecerte un espacio seguro, confidencial y libre de juicios. Atiendo a adultos y adultos mayores, tanto de forma presencial en Altabrisa como en línea.',
    languages: ['Español', 'Inglés'],
    nextAvailable: 'Mañana, 10:00 AM',
    verified: true,
    tags: ['Ansiedad', 'Estrés', 'Mindfulness', 'TCC'],
    phone: '+52 999 234-5678',
    reviews: [
      { id: 'r1', author: 'Carlos M.', rating: 5, date: '2024-11-15', comment: 'La Dra. García me ayudó a superar una crisis de ansiedad muy difícil. Su enfoque es cálido y profesional. Totalmente recomendada.', verified: true },
      { id: 'r2', author: 'Sofía R.', rating: 5, date: '2024-10-28', comment: 'Excelente profesional. Me dio herramientas reales para manejar el estrés laboral. Las sesiones en línea son muy cómodas.', verified: true },
      { id: 'r3', author: 'Miguel T.', rating: 4, date: '2024-09-12', comment: 'Muy buena experiencia. La doctora escucha con atención y explica todo muy claramente. El precio es justo por la calidad.', verified: false },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: ['09:00', '11:30', '15:00'] },
      { label: 'Mañana 24 jun', slots: ['10:00', '14:30'] },
      { label: 'Mié 25 jun', slots: [] },
      { label: 'Jue 26 jun', slots: ['09:00', '12:00', '16:00'] },
    ],
  },
  {
    id: '2',
    name: 'Roberto Pérez Mendoza',
    prefix: 'Dr.',
    slug: 'roberto-perez-mendoza',
    initials: 'RP',
    avatarColor: '#7C3AED',
    primarySpecialty: 'Terapia de Pareja',
    specialty: 'Terapia de Pareja',
    specialties: ['Terapia de Pareja', 'Terapia Sexual', 'Comunicación', 'Infidelidad'],
    rating: 4.8,
    reviewCount: 89,
    neighborhood: 'García Ginerés',
    location: 'García Ginerés, Mérida',
    address: 'Calle 17 #312 x 24 y 26, Col. García Ginerés, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Autónoma de Yucatán (UADY)', year: '2005' },
      { degree: 'Maestría en Terapia de Pareja y Familia', institution: 'Instituto Latinoamericano de Estudios de la Familia', year: '2009' },
      { degree: 'Diplomado en Sexología Clínica', institution: 'Universidad de Guadalajara', year: '2012' },
    ],
    cedula: '7123456',
    yearsExperience: 18,
    pricePerSession: 1100,
    price: 1100,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Me especializo en terapia de pareja y sexual con 18 años de experiencia ayudando a parejas a reconectar, comunicarse mejor y superar crisis como la infidelidad o la falta de intimidad. Utilizo el modelo Gottman y la Terapia Focalizada en las Emociones (TFE) para crear cambios duraderos. Creo que toda relación puede mejorar cuando ambas partes se comprometen con el proceso. Atiendo parejas heterosexuales y del mismo sexo, con total respeto y apertura. También ofrezco sesiones individuales para quienes atraviesan rupturas o divorcios.',
    languages: ['Español'],
    nextAvailable: 'Miércoles, 4:00 PM',
    verified: true,
    tags: ['Pareja', 'Comunicación', 'Infidelidad', 'Sexología'],
    phone: '+52 999 345-6789',
    reviews: [
      { id: 'r4', author: 'Ana y Luis P.', rating: 5, date: '2024-11-20', comment: 'El Dr. Pérez salvó nuestra relación. Después de años de conflictos, aprendimos a comunicarnos. Es un profesional excepcional.', verified: true },
      { id: 'r5', author: 'Fernanda G.', rating: 5, date: '2024-10-05', comment: 'Muy empático y sin juicios. Nos ayudó a pasar por un momento muy difícil. Las técnicas que usa son muy efectivas.', verified: true },
      { id: 'r6', author: 'Ricardo V.', rating: 4, date: '2024-08-22', comment: 'Buen profesional, puntual y muy conocedor del tema. El consultorio es muy cómodo y privado. Lo recomiendo ampliamente.', verified: false },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: [] },
      { label: 'Mañana 24 jun', slots: ['09:30', '13:00', '17:00'] },
      { label: 'Mié 25 jun', slots: ['10:00', '16:00'] },
      { label: 'Jue 26 jun', slots: ['11:00'] },
    ],
  },
  {
    id: '3',
    name: 'Sofía Castillo Ávila',
    prefix: 'Dra.',
    slug: 'sofia-castillo-avila',
    initials: 'SC',
    avatarColor: '#DB2777',
    primarySpecialty: 'Psicología Infantil',
    specialty: 'Psicología Infantil',
    specialties: ['Psicología Infantil', 'TDAH Infantil', 'Bullying', 'Problemas de Aprendizaje'],
    rating: 5.0,
    reviewCount: 203,
    neighborhood: 'Centro Histórico',
    location: 'Centro Histórico, Mérida',
    address: 'Calle 60 #485, Centro Histórico, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Autónoma de Yucatán (UADY)', year: '2006' },
      { degree: 'Maestría en Psicología Infantil y del Desarrollo', institution: 'Universidad Nacional Autónoma de México (UNAM)', year: '2010' },
      { degree: 'Certificación en Neuropsicología Infantil', institution: 'Hospital Infantil de México Federico Gómez', year: '2014' },
    ],
    cedula: '7456789',
    yearsExperience: 17,
    pricePerSession: 800,
    price: 800,
    offersOnline: false,
    offersInPerson: true,
    online: false,
    bio: 'Especialista en psicología infantil y del desarrollo con 17 años dedicados a apoyar a niños de 3 a 16 años y sus familias. Trabajo con niños que presentan TDAH, dificultades de aprendizaje, problemas emocionales, bullying y adaptación escolar. Mi consultorio está diseñado especialmente para que los pequeños se sientan seguros y cómodos, utilizando el juego y técnicas lúdicas como herramientas terapéuticas. También ofrezco orientación a padres para que puedan apoyar mejor a sus hijos desde casa. Cada niño es único y merece un plan de tratamiento personalizado.',
    languages: ['Español'],
    nextAvailable: 'Hoy, 3:00 PM',
    verified: true,
    tags: ['Niños', 'TDAH', 'Bullying', 'Aprendizaje'],
    phone: '+52 999 456-7890',
    reviews: [
      { id: 'r7', author: 'Daniela H. (mamá)', rating: 5, date: '2024-12-01', comment: 'La Dra. Castillo es maravillosa con los niños. Mi hijo de 8 años la adora y ha mejorado enormemente en la escuela. 100% recomendada.', verified: true },
      { id: 'r8', author: 'Pedro O. (papá)', rating: 5, date: '2024-11-10', comment: 'Excelente profesional. Diagnosticó el TDAH de mi hija correctamente cuando otros no pudieron. Muy paciente y dedicada.', verified: true },
      { id: 'r9', author: 'Lucía S. (mamá)', rating: 5, date: '2024-10-18', comment: 'Increíble la transformación de mi hijo después de 6 meses con la Dra. Castillo. Su metodología es única y efectiva.', verified: true },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: ['15:00', '16:30'] },
      { label: 'Mañana 24 jun', slots: ['09:00', '10:30', '12:00'] },
      { label: 'Mié 25 jun', slots: ['09:00'] },
      { label: 'Jue 26 jun', slots: [] },
    ],
  },
  {
    id: '4',
    name: 'Alejandro Torres Ruiz',
    prefix: 'Dr.',
    slug: 'alejandro-torres-ruiz',
    initials: 'AT',
    avatarColor: '#2563EB',
    primarySpecialty: 'Trauma y PTSD',
    specialty: 'Trauma y PTSD',
    specialties: ['Trauma y PTSD', 'Violencia', 'EMDR', 'Ansiedad Postraumática'],
    rating: 4.7,
    reviewCount: 64,
    neighborhood: 'Montejo',
    location: 'Montejo, Mérida',
    address: 'Paseo de Montejo #430, Col. Montejo, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología Clínica', institution: 'Universidad Autónoma de Yucatán (UADY)', year: '2009' },
      { degree: 'Maestría en Psicopatología y Salud', institution: 'Universidad de Salamanca, España', year: '2013' },
      { degree: 'Certificación Internacional en EMDR', institution: 'EMDR International Association', year: '2016' },
    ],
    cedula: '8901234',
    yearsExperience: 14,
    pricePerSession: 1200,
    price: 1200,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Especialista en trauma psicológico y trastorno de estrés postraumático (PTSD). Cuento con certificación internacional en EMDR (Desensibilización y Reprocesamiento por Movimientos Oculares), una de las terapias más efectivas y reconocidas para el tratamiento del trauma. He acompañado a sobrevivientes de violencia, accidentes, pérdidas traumáticas y abuso. Trabajo desde un enfoque compasivo y basado en la evidencia, entendiendo que sanar del trauma requiere tiempo, seguridad y un profesional capacitado. Con maestría cursada en España, combino perspectivas internacionales con sensibilidad cultural local.',
    languages: ['Español', 'Inglés'],
    nextAvailable: 'Jueves, 11:00 AM',
    verified: true,
    tags: ['Trauma', 'PTSD', 'EMDR', 'Violencia'],
    phone: '+52 999 567-8901',
    reviews: [
      { id: 'r10', author: 'Carmen L.', rating: 5, date: '2024-11-08', comment: 'El EMDR con el Dr. Torres cambió mi vida. Finalmente pude procesar el trauma que cargaba por años. Profesional y humano a la vez.', verified: true },
      { id: 'r11', author: 'José M.', rating: 5, date: '2024-09-30', comment: 'Muy preparado y con una escucha excepcional. Me ayudó a superar un accidente que me había paralizado emocionalmente.', verified: true },
      { id: 'r12', author: 'Valentina C.', rating: 4, date: '2024-08-15', comment: 'Buen profesional, aunque el precio es alto. Vale la pena por la especialización que tiene. Me sentí segura desde la primera sesión.', verified: false },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: [] },
      { label: 'Mañana 24 jun', slots: [] },
      { label: 'Mié 25 jun', slots: ['11:00', '13:30'] },
      { label: 'Jue 26 jun', slots: ['11:00', '15:00', '17:30'] },
    ],
  },
  {
    id: '5',
    name: 'Valeria López Herrera',
    prefix: 'Dra.',
    slug: 'valeria-lopez-herrera',
    initials: 'VL',
    avatarColor: '#059669',
    primarySpecialty: 'Trastornos Alimenticios',
    specialty: 'Trastornos Alimenticios',
    specialties: ['Trastornos Alimenticios', 'Anorexia', 'Bulimia', 'Imagen Corporal', 'Autoestima'],
    rating: 4.9,
    reviewCount: 142,
    neighborhood: 'Periférico Norte',
    location: 'Periférico Norte, Mérida',
    address: 'Anillo Periférico Norte #2890, Col. Chuburná, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Anáhuac Mayab', year: '2007' },
      { degree: 'Maestría en Trastornos de la Conducta Alimentaria', institution: 'Universidad Nacional Autónoma de México (UNAM)', year: '2011' },
      { degree: 'Diplomado en Nutrición Psicológica', institution: 'Instituto Colombiano del Sistema Nervioso', year: '2015' },
    ],
    cedula: '7890123',
    yearsExperience: 16,
    pricePerSession: 950,
    price: 950,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Psicóloga especializada en trastornos de la conducta alimentaria (TCA) con 16 años de experiencia. Trabajo con pacientes que padecen anorexia, bulimia, trastorno por atracón y dificultades con la imagen corporal. Mi enfoque integra la TCC, la terapia dialéctica conductual (TDC) y la alimentación intuitiva, siempre desde una perspectiva libre de dietas y no gordofóbica. Trabajo en colaboración con nutriólogos y médicos para ofrecer un tratamiento integral. Creo que toda persona merece tener una relación saludable con su cuerpo y la comida, independientemente de su talla o peso.',
    languages: ['Español', 'Inglés'],
    nextAvailable: 'Lunes, 9:00 AM',
    verified: true,
    tags: ['TCA', 'Anorexia', 'Bulimia', 'Imagen Corporal'],
    phone: '+52 999 678-9012',
    reviews: [
      { id: 'r13', author: 'Mariana F.', rating: 5, date: '2024-12-05', comment: 'La Dra. López me salvó la vida, literalmente. Su tratamiento para la anorexia es integral y compasivo. La recomiendo con el corazón.', verified: true },
      { id: 'r14', author: 'Rebeca N.', rating: 5, date: '2024-11-22', comment: 'Por fin encontré a alguien que entiende los TCA sin juzgar. Su enfoque libre de dietas es exactamente lo que necesitaba.', verified: true },
      { id: 'r15', author: 'Isabella K.', rating: 5, date: '2024-10-10', comment: 'Excelente terapeuta. Cambió completamente mi relación con la comida y mi cuerpo. Muy recomendada para TCA.', verified: true },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: ['10:00', '12:30'] },
      { label: 'Mañana 24 jun', slots: ['09:00', '11:00', '14:00'] },
      { label: 'Mié 25 jun', slots: ['10:00', '15:30'] },
      { label: 'Jue 26 jun', slots: [] },
    ],
  },
  {
    id: '6',
    name: 'Daniel Ramírez Cruz',
    prefix: 'Dr.',
    slug: 'daniel-ramirez-cruz',
    initials: 'DR',
    avatarColor: '#D97706',
    primarySpecialty: 'TDAH y Adolescentes',
    specialty: 'TDAH y Adolescentes',
    specialties: ['TDAH', 'Adolescentes', 'Problemas de Conducta', 'Orientación Vocacional'],
    rating: 4.6,
    reviewCount: 78,
    neighborhood: 'Altabrisa',
    location: 'Altabrisa, Mérida',
    address: 'Calle 22 #198, Col. Altabrisa, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Autónoma de Yucatán (UADY)', year: '2010' },
      { degree: 'Especialidad en Neuropsicología', institution: 'Instituto Politécnico Nacional (IPN)', year: '2014' },
      { degree: 'Diplomado en TDAH en Niños y Adultos', institution: 'Fundación por el TDAH', year: '2017' },
    ],
    cedula: '9012345',
    yearsExperience: 13,
    pricePerSession: 750,
    price: 750,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Psicólogo especializado en TDAH (Trastorno por Déficit de Atención e Hiperactividad) en niños, adolescentes y adultos. Con 13 años de experiencia y formación en neuropsicología, ofrezco evaluaciones diagnósticas completas y tratamiento psicológico basado en evidencia. Trabajo con adolescentes en temas de conducta, autoestima, relaciones sociales y orientación vocacional. Mi consultorio es un espacio donde los jóvenes se sienten escuchados y comprendidos, sin ser juzgados. También brindo orientación a padres y coordinación con escuelas para apoyar el desarrollo integral del adolescente.',
    languages: ['Español'],
    nextAvailable: 'Viernes, 2:00 PM',
    verified: true,
    tags: ['TDAH', 'Adolescentes', 'Neuropsicología', 'Conducta'],
    phone: '+52 999 789-0123',
    reviews: [
      { id: 'r16', author: 'Tomás A. (papá)', rating: 5, date: '2024-11-18', comment: 'El Dr. Ramírez diagnosticó el TDAH de mi hijo de 14 años y ha mejorado muchísimo en la escuela. Muy buen profesional.', verified: true },
      { id: 'r17', author: 'Gabriela E. (mamá)', rating: 4, date: '2024-10-02', comment: 'Buen psicólogo con mucha experiencia en adolescentes. Mi hijo se abrió con él desde el principio, lo cual es difícil a esa edad.', verified: true },
      { id: 'r18', author: 'Héctor J.', rating: 5, date: '2024-09-05', comment: 'Como adulto con TDAH, finalmente encontré a alguien que entiende mis desafíos. Sus estrategias son prácticas y funcionan.', verified: false },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: ['14:00'] },
      { label: 'Mañana 24 jun', slots: [] },
      { label: 'Mié 25 jun', slots: ['09:00', '10:30', '13:00'] },
      { label: 'Jue 26 jun', slots: ['14:00', '16:00'] },
    ],
  },
  {
    id: '7',
    name: 'Patricia Morales Gómez',
    prefix: 'Dra.',
    slug: 'patricia-morales-gomez',
    initials: 'PM',
    avatarColor: '#DC2626',
    primarySpecialty: 'Duelo y Pérdida',
    specialty: 'Duelo y Pérdida',
    specialties: ['Duelo y Pérdida', 'Depresión', 'Crisis Existencial', 'Enfermedad Terminal'],
    rating: 4.8,
    reviewCount: 156,
    neighborhood: 'Itzimná',
    location: 'Itzimná, Mérida',
    address: 'Calle 35 #287, Col. Itzimná, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Marista de Mérida', year: '2004' },
      { degree: 'Maestría en Psicología Humanista', institution: 'Universidad Iberoamericana', year: '2008' },
      { degree: 'Especialidad en Tanatología', institution: 'Asociación Mexicana de Tanatología', year: '2011' },
    ],
    cedula: '6789012',
    yearsExperience: 19,
    pricePerSession: 850,
    price: 850,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Psicóloga humanista y tanatóloga con 19 años de experiencia acompañando a personas en procesos de duelo y pérdida. He trabajado con personas que han perdido seres queridos, que atraviesan enfermedades graves o terminales, divorcios, pérdida de empleo y otras transiciones dolorosas de la vida. Creo en la capacidad de cada persona para encontrar sentido y fortaleza incluso en los momentos más oscuros. Mi enfoque combina la psicología humanista de Carl Rogers con la logoterapia de Viktor Frankl, creando un espacio de profunda escucha y acompañamiento. También ofrezco talleres grupales de duelo mensualmente.',
    languages: ['Español'],
    nextAvailable: 'Martes, 5:00 PM',
    verified: true,
    tags: ['Duelo', 'Pérdida', 'Tanatología', 'Humanismo'],
    phone: '+52 999 890-1234',
    reviews: [
      { id: 'r19', author: 'Elena B.', rating: 5, date: '2024-12-03', comment: 'La Dra. Morales me acompañó en el duelo por mi mamá con una sensibilidad extraordinaria. Su presencia es sanadora. Gracias de corazón.', verified: true },
      { id: 'r20', author: 'Antonio R.', rating: 5, date: '2024-11-25', comment: 'Después de perder a mi esposa, no sabía cómo seguir. La Dra. Morales me ayudó a encontrar un camino. Profesional increíble.', verified: true },
      { id: 'r21', author: 'Laura M.', rating: 4, date: '2024-09-20', comment: 'Muy empática y con un enfoque diferente al de otros psicólogos. Me ayudó a procesar un divorcio difícil. Altamente recomendada.', verified: true },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: [] },
      { label: 'Mañana 24 jun', slots: ['17:00', '18:30'] },
      { label: 'Mié 25 jun', slots: ['16:00'] },
      { label: 'Jue 26 jun', slots: ['09:00', '10:00', '17:00'] },
    ],
  },
  {
    id: '8',
    name: 'Eduardo Fuentes Díaz',
    prefix: 'Dr.',
    slug: 'eduardo-fuentes-diaz',
    initials: 'EF',
    avatarColor: '#0891B2',
    primarySpecialty: 'Terapia Familiar',
    specialty: 'Terapia Familiar',
    specialties: ['Terapia Familiar', 'Comunicación Familiar', 'Crianza Positiva', 'Conflictos Intergeneracionales'],
    rating: 4.7,
    reviewCount: 91,
    neighborhood: 'Cholul',
    location: 'Cholul, Mérida',
    address: 'Calle Principal #45, Com. Cholul, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Autónoma de Yucatán (UADY)', year: '2008' },
      { degree: 'Maestría en Terapia Familiar Sistémica', institution: 'Universidad del Valle de México', year: '2012' },
      { degree: 'Diplomado en Mediación Familiar', institution: 'Colegio de Psicólogos de Yucatán', year: '2015' },
    ],
    cedula: '8567890',
    yearsExperience: 15,
    pricePerSession: 1000,
    price: 1000,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Terapeuta familiar sistémico con 15 años de experiencia trabajando con familias en crisis, conflictos intergeneracionales y dificultades de comunicación. Mi enfoque sistémico me permite ver a la familia como un todo interconectado, donde el bienestar de uno afecta a todos. Trabajo con familias nucleares, monoparentales, reconstituidas y de diferentes configuraciones, siempre desde el respeto y la neutralidad. También brindo orientación en crianza positiva para padres que buscan mejorar su relación con sus hijos. Las sesiones pueden realizarse con toda la familia o con subgrupos, según las necesidades del momento.',
    languages: ['Español'],
    nextAvailable: 'Miércoles, 6:00 PM',
    verified: true,
    tags: ['Familia', 'Sistémica', 'Crianza', 'Comunicación'],
    phone: '+52 999 901-2345',
    reviews: [
      { id: 'r22', author: 'Familia Sánchez', rating: 5, date: '2024-11-30', comment: 'El Dr. Fuentes transformó la dinámica de nuestra familia. Aprendimos a escucharnos y respetarnos. Increíble profesional.', verified: true },
      { id: 'r23', author: 'Martha P.', rating: 5, date: '2024-10-15', comment: 'Gracias al Dr. Fuentes, mejoró enormemente la relación con mis hijos adolescentes. Sus técnicas de comunicación son muy prácticas.', verified: true },
      { id: 'r24', author: 'Roberto S.', rating: 4, date: '2024-08-28', comment: 'Muy buen terapeuta familiar. Logró que mi esposa y yo pudiéramos hablar sin pelear. La distancia desde el centro es un poco lejos, pero vale la pena.', verified: false },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: ['18:00'] },
      { label: 'Mañana 24 jun', slots: ['10:00', '12:00'] },
      { label: 'Mié 25 jun', slots: ['18:00'] },
      { label: 'Jue 26 jun', slots: [] },
    ],
  },
  {
    id: '9',
    name: 'Isabela Vargas Reyes',
    prefix: 'Dra.',
    slug: 'isabela-vargas-reyes',
    initials: 'IV',
    avatarColor: '#0D9488',
    primarySpecialty: 'Depresión y Bienestar Emocional',
    specialty: 'Depresión y Bienestar Emocional',
    specialties: ['Depresión y Bienestar Emocional', 'Ansiedad', 'Autoestima', 'Duelo', 'Manejo Emocional'],
    rating: 4.8,
    reviewCount: 112,
    neighborhood: 'Cordemex',
    location: 'Cordemex, Mérida',
    address: 'Calle 41 #320, Col. Cordemex, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Autónoma de Yucatán (UADY)', year: '2009' },
      { degree: 'Maestría en Psicología Clínica y de la Salud', institution: 'Universidad Nacional Autónoma de México (UNAM)', year: '2013' },
      { degree: 'Diplomado en Terapia de Activación Conductual para la Depresión', institution: 'Instituto Mexicano de Psicoterapia Cognitivo Conductual', year: '2016' },
    ],
    cedula: '9234561',
    yearsExperience: 14,
    pricePerSession: 800,
    price: 800,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Soy psicóloga clínica con 14 años de experiencia especializada en el tratamiento de la depresión y la promoción del bienestar emocional. He acompañado a cientos de personas a salir de los momentos más oscuros de su vida, recuperando la motivación, el disfrute y el sentido. Utilizo un enfoque integrativo que combina la Terapia Cognitivo-Conductual, la Activación Conductual y técnicas de Psicología Positiva, adaptadas a cada persona de manera individual. Creo profundamente que la depresión tiene tratamiento y que la vida puede volver a tener color. Atiendo tanto de manera presencial en Cordemex como en línea, para mayor comodidad de mis pacientes. Mi consultorio es un espacio donde no hay prisa, solo escucha genuina y trabajo conjunto hacia tu bienestar.',
    languages: ['Español', 'Inglés'],
    nextAvailable: 'Hoy, 4:00 PM',
    verified: true,
    tags: ['Depresión', 'Bienestar', 'Autoestima', 'TCC'],
    phone: '+52 999 112-3344',
    reviews: [
      { id: 'r25', author: 'Claudia N.', rating: 5, date: '2024-12-08', comment: 'La Dra. Vargas me devolvió las ganas de vivir. Llevaba dos años con depresión y gracias a su acompañamiento volví a ser yo misma. Eternamente agradecida.', verified: true },
      { id: 'r26', author: 'Ernesto P.', rating: 5, date: '2024-11-14', comment: 'Profesional excepcional. Explica todo con claridad, es muy empática y las herramientas que da son prácticas y reales. Mi vida mejoró mucho.', verified: true },
      { id: 'r27', author: 'Diana L.', rating: 4, date: '2024-10-03', comment: 'Muy buena experiencia. La doctora tiene una calidad humana enorme y se nota que le apasiona lo que hace. Las sesiones en línea funcionan muy bien.', verified: false },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: ['16:00', '17:30'] },
      { label: 'Mañana 24 jun', slots: ['09:00', '11:00', '13:30'] },
      { label: 'Mié 25 jun', slots: ['10:00'] },
      { label: 'Jue 26 jun', slots: ['09:00', '15:00'] },
    ],
  },
  {
    id: '10',
    name: 'Rodrigo Peña Sandoval',
    prefix: 'Dr.',
    slug: 'rodrigo-pena-sandoval',
    initials: 'RP',
    avatarColor: '#9333EA',
    primarySpecialty: 'Psicología Organizacional',
    specialty: 'Psicología Organizacional',
    specialties: ['Psicología Organizacional', 'Burnout Laboral', 'Liderazgo', 'Estrés Laboral', 'Coaching Ejecutivo'],
    rating: 4.7,
    reviewCount: 85,
    neighborhood: 'Ciudad Industrial',
    location: 'Ciudad Industrial, Mérida',
    address: 'Calle 59-A #180, Col. Ciudad Industrial, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología Organizacional', institution: 'Universidad Anáhuac Mayab', year: '2007' },
      { degree: 'Maestría en Psicología del Trabajo y las Organizaciones', institution: 'Universidad Iberoamericana', year: '2011' },
      { degree: 'Certificación en Coaching Ejecutivo', institution: 'International Coaching Federation (ICF) México', year: '2015' },
    ],
    cedula: '8345672',
    yearsExperience: 16,
    pricePerSession: 1050,
    price: 1050,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Soy psicólogo organizacional y coach ejecutivo certificado con 16 años de experiencia ayudando a profesionistas, directivos y equipos de trabajo a alcanzar su máximo potencial sin sacrificar su salud mental. Me especializo en el manejo del burnout laboral, el liderazgo consciente y la gestión del estrés en entornos de alta demanda. Trabajo con ejecutivos, emprendedores y personas en transición de carrera que buscan alinear su vida profesional con su bienestar personal. Mi enfoque combina la psicología basada en evidencia con herramientas de coaching que generan resultados concretos y sostenibles. He colaborado con empresas y organizaciones de Yucatán ofreciendo talleres y programas de bienestar laboral. Creo que un profesionista saludable es un profesionista productivo.',
    languages: ['Español', 'Inglés'],
    nextAvailable: 'Mañana, 9:00 AM',
    verified: true,
    tags: ['Burnout', 'Liderazgo', 'Estrés Laboral', 'Coaching'],
    phone: '+52 999 223-4455',
    reviews: [
      { id: 'r28', author: 'Gerardo M.', rating: 5, date: '2024-12-02', comment: 'El Dr. Peña me ayudó a superar un burnout severo y a redefinir mis prioridades laborales. Es un profesional de primer nivel con una visión muy completa.', verified: true },
      { id: 'r29', author: 'Ximena A.', rating: 5, date: '2024-11-07', comment: 'Increíble el cambio que logré en pocos meses. Aprendí a liderar con menos estrés y a cuidarme sin dejar de ser productiva. Totalmente recomendado.', verified: true },
      { id: 'r30', author: 'Marcos V.', rating: 4, date: '2024-09-19', comment: 'Muy buen profesional. Sus sesiones son claras, estructuradas y con resultados concretos. El precio es alto pero completamente justificado.', verified: false },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: [] },
      { label: 'Mañana 24 jun', slots: ['09:00', '10:30', '12:00'] },
      { label: 'Mié 25 jun', slots: ['08:30', '14:00'] },
      { label: 'Jue 26 jun', slots: ['09:00', '11:00', '16:30'] },
    ],
  },
  {
    id: '11',
    name: 'Luciana Espinoza Nava',
    prefix: 'Dra.',
    slug: 'luciana-espinoza-nava',
    initials: 'LE',
    avatarColor: '#E11D48',
    primarySpecialty: 'Sexología Clínica',
    specialty: 'Sexología Clínica',
    specialties: ['Sexología Clínica', 'Disfunciones Sexuales', 'Identidad de Género', 'Salud Sexual', 'Terapia de Pareja'],
    rating: 4.9,
    reviewCount: 73,
    neighborhood: 'Santiago',
    location: 'Santiago, Mérida',
    address: 'Calle 71 #508 x 60 y 62, Col. Santiago, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Autónoma de Yucatán (UADY)', year: '2010' },
      { degree: 'Maestría en Psicología Clínica', institution: 'Universidad Nacional Autónoma de México (UNAM)', year: '2014' },
      { degree: 'Especialidad en Sexología Clínica', institution: 'Instituto Mexicano de Sexología (IMESEX)', year: '2017' },
    ],
    cedula: '9456783',
    yearsExperience: 12,
    pricePerSession: 950,
    price: 950,
    offersOnline: true,
    offersInPerson: true,
    online: true,
    bio: 'Soy psicóloga clínica y sexóloga certificada con 12 años de experiencia abordando la sexualidad humana desde una perspectiva integral, científica y libre de tabúes. Me especializo en el tratamiento de disfunciones sexuales, problemas de deseo, dolor en las relaciones íntimas, dificultades con la identidad de género y la orientación sexual. Acompaño tanto a personas individuales como a parejas en la exploración y mejora de su vida sexual y afectiva. Mi consultorio en Santiago es un espacio completamente confidencial y libre de juicios, donde cada persona puede hablar con absoluta libertad. Trabajo con una perspectiva de género, diversidad e inclusión, atendiendo a personas de todas las orientaciones e identidades. La sexualidad es una parte fundamental del bienestar humano y merece ser atendida con la misma seriedad que cualquier otra área de la salud.',
    languages: ['Español'],
    nextAvailable: 'Miércoles, 3:00 PM',
    verified: true,
    tags: ['Sexología', 'Disfunciones Sexuales', 'Diversidad', 'Pareja'],
    phone: '+52 999 334-5566',
    reviews: [
      { id: 'r31', author: 'Paola R.', rating: 5, date: '2024-12-10', comment: 'La Dra. Espinoza es increíblemente profesional y empática. Por fin encontré un espacio donde hablar de sexualidad sin vergüenza. Cambió mi vida de pareja.', verified: true },
      { id: 'r32', author: 'Andrés y Camila T.', rating: 5, date: '2024-11-01', comment: 'Fuimos como pareja y fue una experiencia transformadora. La doctora maneja temas muy delicados con una sensibilidad y profesionalismo admirables.', verified: true },
      { id: 'r33', author: 'Natalia F.', rating: 5, date: '2024-09-25', comment: 'Gracias a la Dra. Espinoza pude entender y aceptar aspectos de mi identidad que tenía reprimidos. Un trabajo terapéutico profundo y respetuoso.', verified: false },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: ['11:00', '13:00'] },
      { label: 'Mañana 24 jun', slots: [] },
      { label: 'Mié 25 jun', slots: ['15:00', '16:30', '18:00'] },
      { label: 'Jue 26 jun', slots: ['10:00', '12:00'] },
    ],
  },
  {
    id: '12',
    name: 'Gustavo Montes Ibarra',
    prefix: 'Dr.',
    slug: 'gustavo-montes-ibarra',
    initials: 'GM',
    avatarColor: '#78716C',
    primarySpecialty: 'Adicciones y Salud Mental',
    specialty: 'Adicciones y Salud Mental',
    specialties: ['Adicciones y Salud Mental', 'Alcoholismo', 'Dependencias Químicas', 'Recaída y Prevención', 'Motivación al Cambio'],
    rating: 4.6,
    reviewCount: 58,
    neighborhood: 'La Ermita',
    location: 'La Ermita, Mérida',
    address: 'Calle 65 #441, Col. La Ermita, Mérida, Yucatán',
    education: [
      { degree: 'Licenciatura en Psicología', institution: 'Universidad Autónoma de Yucatán (UADY)', year: '2006' },
      { degree: 'Maestría en Psicología de las Adicciones', institution: 'Universidad Nacional Autónoma de México (UNAM)', year: '2010' },
      { degree: 'Diplomado en Entrevista Motivacional y Prevención de Recaídas', institution: 'Centro Nacional para la Prevención y Control de las Adicciones (CENADIC)', year: '2013' },
    ],
    cedula: '7678904',
    yearsExperience: 17,
    pricePerSession: 700,
    price: 700,
    offersOnline: false,
    offersInPerson: true,
    online: false,
    bio: 'Soy psicólogo especializado en adicciones y salud mental con 17 años de experiencia acompañando a personas y familias en el camino hacia la recuperación. Trabajo con personas que enfrentan dependencia al alcohol, drogas, conductas compulsivas y otras adicciones, utilizando la Entrevista Motivacional, la Terapia Cognitivo-Conductual y el modelo de Prevención de Recaídas de Marlatt. Entiendo que la adicción es una enfermedad compleja que afecta no solo a quien la padece, sino a toda la familia, por lo que también ofrezco orientación a familiares y personas codependientes. Mi consultorio en La Ermita es un espacio de absoluta confidencialidad, sin estigmas y con total respeto por el proceso único de cada persona. Creo firmemente en la capacidad de recuperación del ser humano y he sido testigo de transformaciones profundas que demuestran que siempre hay una salida.',
    languages: ['Español'],
    nextAvailable: 'Jueves, 10:00 AM',
    verified: true,
    tags: ['Adicciones', 'Alcoholismo', 'Recuperación', 'Familia'],
    phone: '+52 999 445-6677',
    reviews: [
      { id: 'r34', author: 'Familia Ortega', rating: 5, date: '2024-11-28', comment: 'El Dr. Montes acompañó a nuestro hijo en su proceso de recuperación del alcoholismo con una paciencia y humanidad excepcionales. Hoy está sobrio gracias a su trabajo.', verified: true },
      { id: 'r35', author: 'Ramón E.', rating: 4, date: '2024-10-22', comment: 'Llevo 8 meses en tratamiento y es la primera vez que siento que realmente puedo lograrlo. El doctor me trata con dignidad y eso hace toda la diferencia.', verified: true },
      { id: 'r36', author: 'Silvia C.', rating: 5, date: '2024-09-08', comment: 'Fui como familiar de un adicto y el Dr. Montes me ayudó a entender la enfermedad y a dejar de ser codependiente. Cambió mi perspectiva completamente.', verified: false },
    ],
    availability: [
      { label: 'Hoy 23 jun', slots: [] },
      { label: 'Mañana 24 jun', slots: ['10:00', '12:00'] },
      { label: 'Mié 25 jun', slots: [] },
      { label: 'Jue 26 jun', slots: ['10:00', '11:30', '15:00'] },
    ],
  },
];
